baseURL: https://justifiedsolutions.com/
languageCode: en-us
title: Justified Solutions
copyright: "© 2023 Justified Solutions, LLC"

disableKinds:
  - RSS
  - sitemap
  - robotsTXT

taxonomies:
  tag: tags

params:
  headerImage: "/images/js-logo.png"

menu:
  left:
    - identifier: home
      name: "Home"
      url: "/"
      weight: 1
    - identifier: sfspro
      name: "SFS Pro"
      url: "/sfspro/"
      weight: 2
    - identifier: licensing
      name: "Licensing"
      url: "/sfspro/licensing/"
      parent: sfspro
      weight: 1
    - identifier: screenshots
      name: "Screenshots"
      url: "/sfspro/screenshots/"
      parent: sfspro
      weight: 2
    - identifier: example-output
      name: "Example Output"
      url: "/sfspro/example-output/"
      parent: sfspro
      weight: 3
    - identifier: open-source
      name: "Open Source"
      url: "/open-source/"
      weight: 3
  right:
    - identifier: support
      name: "Support"
      url: "/support/"
      weight: 4
    - identifier: contact
      name: "Contact"
      url: "/contact/"
      weight: 5
